# Generated by Django 5.2.17 on 2026-08-06 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cidr', models.CharField(help_text='Explicit IPv4/IPv6 network or host target.', max_length=43)),
                ('enabled', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('source', models.CharField(choices=[('home_assistant', 'Home Assistant'), ('arp', 'ARP'), ('manual', 'Manual')], max_length=20)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['ip_address'],
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'source'), name='unique_device_source')],
            },
        ),
        migrations.CreateModel(
            name='MonitoredEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down')], default='unknown', max_length=12)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='dashboard.monitoredendpoint')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_up', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='dashboard.monitoredendpoint')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
