# Generated by Django 5.2.17 on 2026-08-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereddevice',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discovereddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='discovereddevice',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id', 'source'), name='unique_external_device_source'),
        ),
    ]
